apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  # The hostname must match the Service name defined in 02-mysql.yaml
  DATABASE_HOST: "mysql-service"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "my_django_db"
  DATABASE_USER: "anish"
