apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
# In a real production scenario, these should be encrypted. 
# For learning/kind, we use plain text stringData.
stringData:
  # This is the password for the 'anish' user
  DATABASE_PASSWORD: "anish123"
  # This is the root password for MySQL setup
  MYSQL_ROOT_PASSWORD: "anish123"